baseURL: 'https://danielmehnert.de/'
languageCode: de
title: danielmehnert.de
theme: PaperMod

params:
  env: development # to enable google analytics, opengraph, twitter-cards and schema.
  title: danielmehnert.de
  description: "personal profile page"
  keywords: [Blog, Portfolio, PaperMod]
  author: Daniel Mehnert
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Daniel Mehnert
    subtitle: "Koppelweg 45 - 27305 Bruchhausen-Vilsen"
    imageUrl: "/img/profile.jpeg"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Daniel Mehnert's profile picture
      
    
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my public profile page

  socialIcons:
    - name: email
      url: "mailto:mail@danielmehnert.de"
    - name: phone
      url: "tel:+49163-8631698"
    - name: mastodon
      url: "https://ieji.de/@secutor"
    - name: twitter
      url: "https://twitter.com/danielmehnert"
    - name: linkedin
      url: "http://www.linkedin.com/pub/daniel-mehnert/11/429/b"
    - name: xing
      url: "http://www.xing.com/profile/Daniel_Mehnert"
    - name: googlescholar
      url: "https://scholar.google.de/citations?user=kZ5ecLUAAAAJ"
    


  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/secutor/danielmehnert.de/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: blog
      url: /posts/
      weight: 10
    
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
